var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/018h_next_dist_1qwgya6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0da0-ss._.js")
R.c("server/chunks/ssr/018h_next_dist_esm_server_140-czd._.js")
R.c("server/chunks/ssr/018h_next_dist_esm_lib_06d6nby._.js")
R.c("server/chunks/ssr/018h_next_dist_esm_0v8skhq._.js")
R.c("server/chunks/ssr/018h_next_dist_compiled_13h-7g-._.js")
R.c("server/chunks/ssr/018h_next_dist_server_route-modules_app-page_082sti9._.js")
R.c("server/chunks/ssr/[externals]__0p9puhg._.js")
R.c("server/chunks/ssr/experiences_dissertation-books_1m6frea._.js")
R.c("server/chunks/ssr/018h_next_dist_client_components_1qeoml2._.js")
R.c("server/chunks/ssr/018h_next_dist_client_components_builtin_forbidden_0_vhn7r.js")
R.c("server/chunks/ssr/018h_next_dist_client_components_builtin_unauthorized_06zkr-6.js")
R.c("server/chunks/ssr/018h_next_dist_client_components_builtin_global-error_15ra7d9.js")
R.c("server/chunks/ssr/experiences_dissertation-books__next-internal_server_app_page_actions_07dii8g.js")
R.m("[project]/experiences/dissertation-books/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { MODULE_0 => \"[project]/experiences/dissertation-books/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/experiences/dissertation-books/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/experiences/dissertation-books/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/experiences/dissertation-books/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/experiences/dissertation-books/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/experiences/dissertation-books/app/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/experiences/dissertation-books/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { MODULE_0 => \"[project]/experiences/dissertation-books/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/experiences/dissertation-books/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/experiences/dissertation-books/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/experiences/dissertation-books/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/experiences/dissertation-books/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/experiences/dissertation-books/app/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
